server:
  port: 8080

spring:
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      uri: mongodb://localhost:27017/challenge-db
      database: challenge-db
      
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1