server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  zipkin:
    base-url: http://zipkinserver:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authservice:8080

auth-issuer-ui: http://authservice:8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eurekaservice:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    
encrypt:
  secret:
    key: MySecretKey12345


management:
  tracing:
    sampling:
      probability: 1