server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
          
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
