server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  zipkin:
      base-url: ${ZIPKIN_SERVER_ADDRESS:http://localhost:9411}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_PATH:http://localhost:8080}

auth-issuer-ui: ${AUTH_SERVICE_PATH:http://localhost:8080}
mongo-server-uri: ${MONGO_SERVER_ADDRESS:mongodb://localhost:27017}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    
management:
  tracing:
    sampling:
      probability: 1